### ISSUE TITLE
Build fails update the container image

### ISSUE THREAD

**Issue by edbergavera** [CircleCI-Public/aws-eks-orb#48]
### Orb version

circleci/aws-eks@1.1.0

### What happened

We noticed today our deployments are failing. We've been using the Orb aws-eks: circleci/aws-eks@1.1.0 to update container images on the EKS cluster without issues until today. We are seeing the kubectl command includes an argument `--dry-run`, which is not set in the CI configuration. We tried setting up a variable through context and project level, but that doesn't seem to work either.

https://app.circleci.com/pipelines/github/b-eee/sleep-partners/156/workflows/39411f04-e7cf-4eed-a7f9-fd18be342bac/jobs/275

### Expected behavior

Should be able to update the container image with `dry-run` argument is deactivated or set to none.

**Comment by ahacop** [comment]
See: https://github.com/CircleCI-Public/kubernetes-orb/issues/51

**Comment by edbergavera** [comment]
@ahacop, thanks for pointing out the related issue. Any update on when we can expect the fix?

**Comment by HennaAbbas** [comment]
@edbergavera Thanks for your patience. We are currently working on a fix. @brivu will follow up with an update shortly.

**Comment by amanfredi** [comment]
Hey folks, this is a pretty simple fix since the kubernetes/install command from the k8s orb already supports a parameter to pin the kubectl version. 
`kubectl-version: v1.22.4`
I forked this repo and published a fixed orb to unblock our deploys, if anyone else wants to use it while we wait for the official fix.

https://github.com/transfixio/aws-eks-orb
https://circleci.com/developer/orbs/orb/transfix/aws-eks
@edbergavera @parkerjm @ahacop

**Comment by edbergavera** [comment]
@amanfredi looks good to me. I will try this out. A workaround referenced by @ahacop to pin the k8s version (before v1.23) for those using Kubernetes Orb. But I think making the `--dry-run` argument optional should resolve the issue. A long-term solution might be changing the `--dry-run` argument into a string that can be set to a valid value compatible with k8s v1.23 upwards.

**Comment by tomahawk-pilot** [comment]
can we expedite this ?? @ahacop

**Comment by ahacop** [comment]
> can we expedite this ?? @ahacop

"We" don't work at CircleCI, so "we" can't expedite sh*t.

**Comment by emir-hasanbegovic** [comment]
The fix is in: https://circleci.com/developer/orbs/orb/circleci/kubernetes?version=1.0.0
Please update this orb!!

**Comment by parkerjm** [comment]
seems the fix is slated to go into the eks orb rewrite (v2.0), but I hope there is a new minor version released as well. way more risky to upgrade to a full rewrite than patch the k8s orb version the current state

**Comment by HennaAbbas** [comment]
I just wanted to follow up here. We resolved this issue : [update-container-image command fails due to the new kubectl version](https://github.com/CircleCI-Public/kubernetes-orb/issues/51) with the following [PR](https://github.com/CircleCI-Public/kubernetes-orb/pull/53) to the [CircleCI Kubernetes Orb](https://circleci.com/developer/orbs/orb/circleci/kubernetes). We are working on pushing an update to this orb to resolve the issue completely. Thanks @ahacop for the workaround and everyone else for chiming in. Cheers!

**Comment by tomahawk-pilot** [comment]
@HennaAbbas any update on the fix  ?

**Comment by brivu** [comment]
Hi Everyone!  

I'm Brian from the CircleCI Customer Engineering Team.  I've been working on a major update to this Orb the past few weeks and have addressed this issue.  The fix is in place and we're just waiting for the tests to complete before we deploy.  The tests are running as we speak and should be done in a few hours barring any failures.  

Thank you for patience and I'll be sure to check back with more updates.

Best, 
Brian 

(cc: @tomahawk-pilot @parkerjm @emir-hasanbegovic @ahacop @edbergavera @amanfredi)

**Comment by parkerjm** [comment]
@brivu hey Brian, thanks for all your hard work on this! will this major update be backwards compatible with current job definitions?

**Comment by brivu** [comment]
Hey @parkerjm, 

The focus of this update was to make everything current (CLI version, command flags etc) and so there may be some breaking changes.  Having said that, I'm adding the fix to this current version to help you all get back up and running.  

I'm hoping to get this out by EOD or early tomorrow.

Best, 
Brian

**Comment by amritesh-zealous** [comment]
Any updates on this @brivu ?

**Comment by brivu** [comment]
Hey Everyone, 

With this older version, there's an issue with Helm.  Helm 2 has been deprecated and so I am rewriting this patch/minor release without Helm 2 to get you all back up and running.  Thanks again for your continued patience!

-Brian

**Comment by brivu** [comment]
Hi everyone! 

I've finished the patch update.  All checks have passed and I'm just waiting for my Team to do a PR.  After that, you all should be good to go!!!

Best, 
Brian 

@tomahawk-pilot @parkerjm @emir-hasanbegovic @ahacop @edbergavera @amanfredi @amritesh-zealous

**Comment by edbergavera** [comment]
@brivu Thanks for the great update! We appreciate the effort. But are the changes backward compatible with the current version `aws-eks@1.1.0` or should we wait for an Orb version update?

**Comment by tomahawk-pilot** [comment]
@brivu when can we expect this update ?

**Comment by brivu** [comment]
Hi Everyone, 

the orb has been published.  If you change your orb version to **1.2.0**, you'll be able to use it.  

@edbergavera, if you're not using helm 2, this orb should work out fine.  Other than updating helm usage to Helm 3, there shouldn't be any other breaking changes.  

Thank you all for your continued patience with this!  Version 2 is coming soon!  

Best, 
Brian 


cc: @tomahawk-pilot @parkerjm @emir-hasanbegovic @ahacop @edbergavera @amanfredi @amritesh-zealous

**Comment by tomahawk-pilot** [comment]
thanks @brivu for the fix.
