### ISSUE TITLE
Reinstate Helm support (or fix the examples)

### ISSUE THREAD

**Issue by gavinclarkeuk** [CircleCI-Public/aws-eks-orb#56]
## What would you like to be added

In the v2 rewrite it looks like helm support has disappeared from this orb, but not from the usage examples. Would be good to have  helm support reinstated.  Would also be really useful if the helm support included optionally running `helm test` against the deployed chart, but I guess that needs a separate ticket on the helm orb.

## Why is this needed

The steps to setup kubeconfig from eks, install the helm client and run helm upgrade (and then run helm test) make sense to bundle together in an orb to reduce build config clutter

**Comment by brivu** [comment]
Hey @gavinclarkeuk, 

Thanks for the note.  While I totally understand where you're coming from, Helm was originally included inside the AWS EKS Orb and did not have an orb of it's own.  However, we created the Helm orb with the eventual goal of installing Helm on other platforms.  

From our team's standpoint, it's more efficient to maintain one repository.  Any updates (or issues) can be done in one place instead of two. 

I'll be removing the examples in my next PR.  

Best, 
Brian
